apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
    name: run-kpt-functions
spec:
    workspaces:
      - name: source
        mountPath: /source
    steps:
      - name: run-kpt-functions
        image: gcr.io/kpt-dev/kpt:latest
        args:
          - fn
          - run
          - $(workspaces.source.path)/exmaple-package
        volumeMounts:
          - name: docker-socket
            mountPath: /var/run/docker.sock
    volumes:
      - name: docker-socket
        hostPath:
            path: /var/run/docker.sock
            type: Socket
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
    name: run-kpt-functions
spec:
    workspaces:
      - name: shared-workspace
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: shared-workspace
        params:
          - name: url
            value: "https://github.com/prachirp/function-export-example.git"
          - name: deleteExisting
            value: "true"
      - name: kpt
        taskRef:
            name: run-kpt-functions
        workspaces:
          - name: source
            workspace: shared-workspace
